/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.text.NumberFormat;
import javax.swing.JOptionPane;

/**
 *
 * @author Vini
 */
public class Tela_principal extends javax.swing.JFrame {

    /**
     * Creates new form Tela_principal
     */
    public Tela_principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextFieldCampoIdade = new javax.swing.JTextField();
        jButtonCalcular = new javax.swing.JButton();
        jLabelInd = new javax.swing.JLabel();
        jLabelHiperMeses = new javax.swing.JLabel();
        jTextFieldCampoRendaAnual = new javax.swing.JTextField();
        jLabelIdade = new javax.swing.JLabel();
        jLabelRendaAnual = new javax.swing.JLabel();
        jTextFieldCampoRendaMensal = new javax.swing.JTextField();
        jLabelRendaMensal = new javax.swing.JLabel();
        jLabelOR = new javax.swing.JLabel();
        jLabelIndCalc = new javax.swing.JLabel();
        jLabelSubCalc = new javax.swing.JLabel();
        jLabelHiperCalc = new javax.swing.JLabel();
        jLabelMensal = new javax.swing.JLabel();
        jLabelAnual = new javax.swing.JLabel();
        jLabelSub1 = new javax.swing.JLabel();
        jLabelHiper1 = new javax.swing.JLabel();
        jLabelMesesmantem = new javax.swing.JLabel();
        jLabelSubMeses = new javax.swing.JLabel();
        jLabelHiperMeses1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Metas para Riqueza");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextFieldCampoIdade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCampoIdadeActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldCampoIdade, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, 40, 30));

        jButtonCalcular.setText("Calcular");
        jButtonCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCalcularActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCalcular, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 20, 80, 30));

        jLabelInd.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabelInd.setText("Independente:");
        getContentPane().add(jLabelInd, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 330, 120, 40));

        jLabelHiperMeses.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabelHiperMeses.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelHiperMeses.setText("0");
        getContentPane().add(jLabelHiperMeses, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 290, 130, 40));

        jTextFieldCampoRendaAnual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCampoRendaAnualActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldCampoRendaAnual, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, 143, 30));

        jLabelIdade.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelIdade.setText("Idade:");
        getContentPane().add(jLabelIdade, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, -1, 30));

        jLabelRendaAnual.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelRendaAnual.setText("Renda Anual");
        getContentPane().add(jLabelRendaAnual, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, -1, 30));

        jTextFieldCampoRendaMensal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCampoRendaMensalActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldCampoRendaMensal, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 120, 143, 30));

        jLabelRendaMensal.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelRendaMensal.setText("Renda Mensal");
        getContentPane().add(jLabelRendaMensal, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 80, -1, 30));

        jLabelOR.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelOR.setText("OU");
        getContentPane().add(jLabelOR, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 120, -1, 30));

        jLabelIndCalc.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabelIndCalc.setText("R$");
        getContentPane().add(jLabelIndCalc, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 330, 180, 40));

        jLabelSubCalc.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabelSubCalc.setText("R$");
        getContentPane().add(jLabelSubCalc, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 250, 180, 40));

        jLabelHiperCalc.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabelHiperCalc.setText("R$");
        getContentPane().add(jLabelHiperCalc, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 290, 180, 40));

        jLabelMensal.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabelMensal.setText("R$");
        getContentPane().add(jLabelMensal, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 160, 140, 40));

        jLabelAnual.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabelAnual.setText("R$");
        getContentPane().add(jLabelAnual, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, 140, 40));

        jLabelSub1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabelSub1.setText("Subacumulador:");
        getContentPane().add(jLabelSub1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, 130, 40));

        jLabelHiper1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabelHiper1.setText("Hiperacumulador:");
        getContentPane().add(jLabelHiper1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 290, 150, 40));

        jLabelMesesmantem.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelMesesmantem.setText("Meses que mantém:");
        getContentPane().add(jLabelMesesmantem, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 210, 130, 40));

        jLabelSubMeses.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabelSubMeses.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelSubMeses.setText("0");
        getContentPane().add(jLabelSubMeses, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 250, 130, 40));

        jLabelHiperMeses1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabelHiperMeses1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelHiperMeses1.setText("Aposentado");
        getContentPane().add(jLabelHiperMeses1, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 320, 130, 40));

        setSize(new java.awt.Dimension(785, 420));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldCampoIdadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCampoIdadeActionPerformed

    }//GEN-LAST:event_jTextFieldCampoIdadeActionPerformed

    private void jButtonCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCalcularActionPerformed

        String textoRendaAnual = jTextFieldCampoRendaAnual.getText();
        String textoRendaMensal = jTextFieldCampoRendaMensal.getText();
        String textoIdade = jTextFieldCampoIdade.getText();
        String textoRenda = null;
        boolean mensal = false;

        if (textoRendaMensal.equals("")) {
            textoRenda = textoRendaAnual;
        } else if (textoRendaAnual.equals("")) {
            textoRenda = textoRendaMensal;
            mensal = true;
        } else {
            JOptionPane.showMessageDialog(this, "Digite apenas Renda anual OU Mensal!");
            return;
        }

        textoRenda = textoRenda.replace(",", ".");

        if (!textoRenda.equals("") || !textoIdade.equals("")) {

            try {
                NumberFormat formatter = NumberFormat.getCurrencyInstance();

                Double rendaAnual = Double.valueOf(textoRenda);
                if (mensal) {
                    rendaAnual = rendaAnual * 12;
                    jLabelAnual.setText(formatter.format(rendaAnual));
                }

                jLabelMensal.setText(formatter.format(rendaAnual / 12));

                Integer idade = Integer.valueOf(textoIdade);
                idade = Math.abs(idade);

                double subAcumulador = (idade * rendaAnual) / 10;
                double hiperAcumulador = subAcumulador * 2;
                double independente = rendaAnual / 0.04;

                jLabelSubCalc.setText(formatter.format(subAcumulador));
                jLabelHiperCalc.setText(formatter.format(hiperAcumulador));
                jLabelIndCalc.setText(formatter.format(independente));
                
                jLabelSubMeses.setText("" + (subAcumulador / (rendaAnual / 12)));
                jLabelHiperMeses.setText("" + (hiperAcumulador / (rendaAnual / 12)));
                mensal = false;

            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Erro: " + e.getMessage());
            }

        } else {
            JOptionPane.showMessageDialog(this, "Campo vazio!");
        }


    }//GEN-LAST:event_jButtonCalcularActionPerformed

    private void jTextFieldCampoRendaAnualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCampoRendaAnualActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCampoRendaAnualActionPerformed

    private void jTextFieldCampoRendaMensalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCampoRendaMensalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCampoRendaMensalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela_principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCalcular;
    private javax.swing.JLabel jLabelAnual;
    private javax.swing.JLabel jLabelHiper1;
    private javax.swing.JLabel jLabelHiperCalc;
    private javax.swing.JLabel jLabelHiperMeses;
    private javax.swing.JLabel jLabelHiperMeses1;
    private javax.swing.JLabel jLabelIdade;
    private javax.swing.JLabel jLabelInd;
    private javax.swing.JLabel jLabelIndCalc;
    private javax.swing.JLabel jLabelMensal;
    private javax.swing.JLabel jLabelMesesmantem;
    private javax.swing.JLabel jLabelOR;
    private javax.swing.JLabel jLabelRendaAnual;
    private javax.swing.JLabel jLabelRendaMensal;
    private javax.swing.JLabel jLabelSub1;
    private javax.swing.JLabel jLabelSubCalc;
    private javax.swing.JLabel jLabelSubMeses;
    private javax.swing.JTextField jTextFieldCampoIdade;
    private javax.swing.JTextField jTextFieldCampoRendaAnual;
    private javax.swing.JTextField jTextFieldCampoRendaMensal;
    // End of variables declaration//GEN-END:variables
}
